apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: blog-web
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`${INGRESS_HOST}`)
    kind: Rule
    services:
    - name: blog-service
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: blog-websecure
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`${INGRESS_HOST}`)
    kind: Rule
    services:
    - name: blog-service
      port: 80
  tls:
    certResolver: myresolver