name: Docker Image CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Repository
      uses: docker/login-action@v1 
      with:
        registry: ${{ secrets.TENCENT_YUN_REGISTRY_HOST }}
        username: ${{ secrets.TENCENT_YUN_REGISTRY_USERNAME }}
        password: ${{ secrets.TENCENT_YUN_REGISTRY_PASSWORD }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: "${{ secrets.TENCENT_YUN_REGISTRY_HOST }}/${{ github.repository }}:latest"
        cache-from: type=registry,ref=${{ secrets.TENCENT_YUN_REGISTRY_HOST }}/${{ github.repository }}:buildcache
        cache-to: type=registry,ref=${{ secrets.TENCENT_YUN_REGISTRY_HOST }}/${{ github.repository }}:buildcache,mode=max
  deploy:
    runs-on: ubuntu-latest
    environment: PROD
    needs: build
    env:
      CloudRunSecretId: "${{ secrets.CLOUDRUN_SECRETID }}"
      CloudRunSecretKey: "${{ secrets.CLOUDRUN_SECRETKEY }}"
      CloudRunEnvId: "${{ secrets.CLOUDRUN_ENVID }}"
      CloudRunServiceName: "${{ secrets.CLOUDRUN_SERVICENAME }}"
      RegistryHost: ${{ secrets.TENCENT_YUN_REGISTRY_HOST }}
      RepoName: ${{ github.repository }}
    if: github.ref_name == 'master'
    steps:
    - name: 渲染 cloudbaserc.json
      run: |
        cat > cloudbaserc.json << EOF
        {
          "envId": "{{ env.CloudRunEnvId }}",
          "framework": {
            "plugins": {
              "client": {
                "use": "@cloudbase/framework-plugin-container",
                "inputs": {
                  "uploadType": "image",
                  "imageInfo": {
                    "imageUrl": "{{ env.RegistryHost }}/{{ env.RepoName }}:latest"
                  },
                  "serviceName": "{{ env.CloudRunServiceName }}",
                  "servicePath": "/",
                  "mode": "low-cost",
                  "cpu": 0.25,
                  "mem": 0.5,
                  "minNum": 0,
                  "maxNum": 2,
                  "containerPort": 80
                }
              }
            }
          }
        }
        EOF
    - name: Deploy to Tencent CloudBase
      uses: TencentCloudBase/cloudbase-action@v2
      with:
        secretId: ${{ secrets.CLOUDRUN_SECRETID }}
        secretKey: ${{ secrets.CLOUDRUN_SECRETKEY }}
        envId: ${{ secrets.CLOUDRUN_ENVID }}