name: Docker Image CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Repository
      uses: docker/login-action@v1 
      with:
        registry: ${{ secrets.TENCENT_YUN_REGISTRY_HOST }}
        username: ${{ secrets.TENCENT_YUN_REGISTRY_USERNAME }}
        password: ${{ secrets.TENCENT_YUN_REGISTRY_PASSWORD }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: "${{ secrets.TENCENT_YUN_REGISTRY_HOST }}/${{ github.repository }}:latest"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref_name == "master" }}
    steps:
    - name: Rolling update   
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd ${{ secrets.WORKPLACE }}
          ./deploy.sh
