name: Build and Deploy
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_REPO: shabbywu/blog
        TARGET_BRANCH: deploy
        BUILD_SCRIPT: npm install && npm run docs:build
        BUILD_DIR: src/.vuepress/dist/
